### PR TITLE
Remove unnecessary files

### PR DESCRIPTION
**Pull request by iAtog**
Several files were removed, such as **IntelliJ IDEA** and maven files, and I added some files to the `.gitignore` so that they are not removed from your project and will not be visible in the repository.

I also added eclipse files to ignore for future contributors and my future contribution.

### CODE REVIEW

**Comment by iAtog** [comment]
> Hey, awesome contribution; forgot to add them to the .gitignore but it makes the repository cleaner, for sure.
> 
> Only one question: was there any reason for deleting the LICENSE-header.txt file? Could you please bring it back, if possible? Thanks and have an awesome day. ~ dejvokep

As I could see it is just the license, I added it to the `.gitignore` so it would not appear in the repository, I guess you use it to place it in your files, but if it is for personal use it is ok to ignore it, anyway it would not be removed from your files, you can also specify it if you want it in the `README.md`, but if you want it in the repository you can confirm me again and I will gladly do it.

**Comment by dejvokep** [comment]
Thanks for the response! Yes, you are right, I will do my best to create some contributing guidelines as soon as possible.

Regarding the file: it is used by the Maven licensing plugin, so it would be awesome if you brought it back.

I will then merge the PR. Thank you :)

**Comment by iAtog** [comment]
It's ready, I've added the file, sorry for the delay.

**Comment by dejvokep** [comment]
No problem, thanks again for your contribution. Have an amazing day :)

**Pull request merged**
